// <auto-generated />
using System;
using CRMApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMApi.Migrations
{
    [DbContext(typeof(DeveloperDbContext))]
    [Migration("20250303181307_InitialCreateDeveloper")]
    partial class InitialCreateDeveloper
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMApi.Domain.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Stack")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("CRMApi.Domain.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateAssigned")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateCanceled")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateCompleted")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStarted")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("DeveloperProject", b =>
                {
                    b.Property<int>("DevelopersAssignedId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsAssignedId")
                        .HasColumnType("int");

                    b.HasKey("DevelopersAssignedId", "ProjectsAssignedId");

                    b.HasIndex("ProjectsAssignedId");

                    b.ToTable("DeveloperProject");
                });

            modelBuilder.Entity("DeveloperProject", b =>
                {
                    b.HasOne("CRMApi.Domain.Models.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersAssignedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMApi.Domain.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsAssignedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
